// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231003075150_learn4")]
    partial class learn4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("webapi.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "member"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Moderator"
                        });
                });

            modelBuilder.Entity("webapi.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            City = "Zhaoguli",
                            ConcurrencyStamp = "314c480f-dad0-4400-9f86-48a6fdd42336",
                            Email = "wkubach0@nature.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ckubach0"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            City = "Paraíso das Águas",
                            ConcurrencyStamp = "6d0a80aa-f79a-4916-8675-23cd8d72c074",
                            Email = "gmickleburgh1@spotify.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "jmickleburgh1"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            City = "Boyarka",
                            ConcurrencyStamp = "f02c733b-9691-48eb-8531-af6f74bd8843",
                            Email = "gdurante2@state.gov",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "wdurante2"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            City = "Seixal",
                            ConcurrencyStamp = "1790c708-1463-4c17-bb10-52158ff6aa18",
                            Email = "iwoollett3@yelp.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "gwoollett3"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            City = "Saint-Pierre",
                            ConcurrencyStamp = "c7c548c4-ad67-4f13-8342-096cc71b7220",
                            Email = "mwrey4@dot.gov",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "awrey4"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            City = "Teminabuan",
                            ConcurrencyStamp = "39a39938-ed86-4d2a-9259-eb78ab0dd60f",
                            Email = "stimlett5@ihg.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mtimlett5"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            City = "Shuangnian",
                            ConcurrencyStamp = "ab07b37d-6f57-4165-9a59-c7233eee13ea",
                            Email = "ltrimbey6@hc360.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "btrimbey6"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            City = "Changqing",
                            ConcurrencyStamp = "27a46963-c501-4439-8539-84492be4d021",
                            Email = "lgirogetti7@example.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cgirogetti7"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            City = "Eusebio Ayala",
                            ConcurrencyStamp = "e313daea-a38c-4259-94ef-5c04b2fa94e7",
                            Email = "rbocken8@nifty.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "tbocken8"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            City = "Higashimurayama-shi",
                            ConcurrencyStamp = "5d90d9cc-c24b-42c4-baf4-2b063e23c1a9",
                            Email = "dsawer9@netvibes.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ssawer9"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            City = "Las Americas",
                            ConcurrencyStamp = "298be058-2274-4d32-9daa-b52627ef4fa4",
                            Email = "pperfecta@goo.ne.jp",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rperfecta"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            City = "Rantepang",
                            ConcurrencyStamp = "5295af3b-61fc-4760-8d9a-b0c87d6507d4",
                            Email = "maxcelb@home.pl",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "naxcelb"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            City = "Dagang",
                            ConcurrencyStamp = "46a13c48-f140-42d1-9440-c6bcb5123d71",
                            Email = "keykelboschc@joomla.org",
                            EmailConfirmed = false,
                            Gender = "Genderqueer",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "meykelboschc"
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            City = "Al Qardāḩah",
                            ConcurrencyStamp = "29f10a11-9d50-484b-9b98-ef60661e6edd",
                            Email = "nbamletd@europa.eu",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cbamletd"
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            City = "Dobryanka",
                            ConcurrencyStamp = "8a7ea1ce-3a4a-4494-a54d-b103d93f21ff",
                            Email = "sgarritleye@qq.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "dgarritleye"
                        },
                        new
                        {
                            Id = 16,
                            AccessFailedCount = 0,
                            City = "Rockford",
                            ConcurrencyStamp = "3a8aaa71-7baa-40b8-af8c-76885501f645",
                            Email = "mlockf@amazon.co.uk",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "klockf"
                        },
                        new
                        {
                            Id = 17,
                            AccessFailedCount = 0,
                            City = "Victoria",
                            ConcurrencyStamp = "fc4bfb6d-aab3-4c4a-89c3-83bc2331c227",
                            Email = "rharbachg@hud.gov",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "pharbachg"
                        },
                        new
                        {
                            Id = 18,
                            AccessFailedCount = 0,
                            City = "Kamālia",
                            ConcurrencyStamp = "4a823257-48a0-47f1-991d-320c73ae8552",
                            Email = "mtomneyh@zdnet.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "stomneyh"
                        },
                        new
                        {
                            Id = 19,
                            AccessFailedCount = 0,
                            City = "Erdao",
                            ConcurrencyStamp = "bf999872-d906-4bfc-ae36-b9f96c9d99a4",
                            Email = "mcestardi@g.co",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bcestardi"
                        },
                        new
                        {
                            Id = 20,
                            AccessFailedCount = 0,
                            City = "Holboo",
                            ConcurrencyStamp = "d7cd7c7d-f181-4e94-98e0-940a85cf0429",
                            Email = "ktopperj@cbc.ca",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rtopperj"
                        },
                        new
                        {
                            Id = 21,
                            AccessFailedCount = 0,
                            City = "Três Coroas",
                            ConcurrencyStamp = "ffc1daee-3938-415e-b446-0acf34131645",
                            Email = "mworthyk@deliciousdays.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kworthyk"
                        },
                        new
                        {
                            Id = 22,
                            AccessFailedCount = 0,
                            City = "Gibgos",
                            ConcurrencyStamp = "a31e1d00-3ef0-4752-92b4-8dfe2710fc83",
                            Email = "kitscovitzl@go.com",
                            EmailConfirmed = false,
                            Gender = "Agender",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mitscovitzl"
                        },
                        new
                        {
                            Id = 23,
                            AccessFailedCount = 0,
                            City = "São João Nepomuceno",
                            ConcurrencyStamp = "d7d80130-fff8-4739-bf06-04a03de08e28",
                            Email = "lfitterm@earthlink.net",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "sfitterm"
                        },
                        new
                        {
                            Id = 24,
                            AccessFailedCount = 0,
                            City = "Sokolo",
                            ConcurrencyStamp = "5d54ec05-7cf7-4eee-b28d-409bd27e78d9",
                            Email = "dthorsbyn@xrea.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "dthorsbyn"
                        },
                        new
                        {
                            Id = 25,
                            AccessFailedCount = 0,
                            City = "Pamplona/Iruña",
                            ConcurrencyStamp = "fec934a3-424d-4fba-83ec-764f479927c8",
                            Email = "apeeryo@rakuten.co.jp",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ppeeryo"
                        },
                        new
                        {
                            Id = 26,
                            AccessFailedCount = 0,
                            City = "Telagasari",
                            ConcurrencyStamp = "c74a2bb0-da5e-4209-a91c-ee60ee9d7e57",
                            Email = "ftathacottp@nytimes.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "dtathacottp"
                        },
                        new
                        {
                            Id = 27,
                            AccessFailedCount = 0,
                            City = "Tikhoretsk",
                            ConcurrencyStamp = "627c1a18-04ec-41aa-a4b1-2bedbedfd2fe",
                            Email = "blingwoodq@jigsy.com",
                            EmailConfirmed = false,
                            Gender = "Genderfluid",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mlingwoodq"
                        },
                        new
                        {
                            Id = 28,
                            AccessFailedCount = 0,
                            City = "Rokytne",
                            ConcurrencyStamp = "82af99b0-dbd8-40ce-845a-efa44a7a0c8e",
                            Email = "jrichesr@tiny.cc",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "krichesr"
                        },
                        new
                        {
                            Id = 29,
                            AccessFailedCount = 0,
                            City = "Motuo",
                            ConcurrencyStamp = "52b1aebf-eca8-4b74-a60e-248c9da60736",
                            Email = "cmaiers@vkontakte.ru",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "lmaiers"
                        },
                        new
                        {
                            Id = 30,
                            AccessFailedCount = 0,
                            City = "Smiltene",
                            ConcurrencyStamp = "de5ef77b-1277-4b09-9725-331afae6dbf5",
                            Email = "pjeannessont@deviantart.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ljeannessont"
                        },
                        new
                        {
                            Id = 31,
                            AccessFailedCount = 0,
                            City = "Río Cuarto",
                            ConcurrencyStamp = "3508b7be-f2ad-4a8e-8ec6-3fe33c3c5fdc",
                            Email = "smolsonu@youku.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bmolsonu"
                        },
                        new
                        {
                            Id = 32,
                            AccessFailedCount = 0,
                            City = "Lugui",
                            ConcurrencyStamp = "62818f7d-ca8b-4796-97c3-bbf9dc85a226",
                            Email = "hgrocockv@bloglines.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "lgrocockv"
                        },
                        new
                        {
                            Id = 33,
                            AccessFailedCount = 0,
                            City = "Dachnoye",
                            ConcurrencyStamp = "9e7bd133-df3d-4f09-956e-046c37ef1fd2",
                            Email = "mlessmarew@prnewswire.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "alessmarew"
                        },
                        new
                        {
                            Id = 34,
                            AccessFailedCount = 0,
                            City = "Modot",
                            ConcurrencyStamp = "cedea50e-0e9a-4c38-9690-5a290002ef07",
                            Email = "jpadfieldx@hud.gov",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cpadfieldx"
                        },
                        new
                        {
                            Id = 35,
                            AccessFailedCount = 0,
                            City = "Marsh Harbour",
                            ConcurrencyStamp = "f12e34be-4fb3-4f3c-b679-1b47e7a05187",
                            Email = "hhaggerwoody@telegraph.co.uk",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "phaggerwoody"
                        },
                        new
                        {
                            Id = 36,
                            AccessFailedCount = 0,
                            City = "Lianzhu",
                            ConcurrencyStamp = "a75c8915-5a2b-4dfc-96c6-b5c40d26172f",
                            Email = "dsandfordz@cnbc.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "lsandfordz"
                        },
                        new
                        {
                            Id = 37,
                            AccessFailedCount = 0,
                            City = "Hněvotín",
                            ConcurrencyStamp = "38b263bf-119f-44ca-ba43-bb8ae34dc606",
                            Email = "kboal10@fda.gov",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bboal10"
                        },
                        new
                        {
                            Id = 38,
                            AccessFailedCount = 0,
                            City = "Sydney",
                            ConcurrencyStamp = "febb69ed-9133-46e2-9ac9-9a0205b66cd8",
                            Email = "echalloner11@ucsd.edu",
                            EmailConfirmed = false,
                            Gender = "Genderqueer",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "gchalloner11"
                        },
                        new
                        {
                            Id = 39,
                            AccessFailedCount = 0,
                            City = "Hechuan",
                            ConcurrencyStamp = "76a441d7-4d4a-488f-9611-4eb9500cba31",
                            Email = "duzzell12@lulu.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "luzzell12"
                        },
                        new
                        {
                            Id = 40,
                            AccessFailedCount = 0,
                            City = "Krajan Timur Suger Kidul",
                            ConcurrencyStamp = "c8d1a6f8-1917-4c37-9d36-ba4001dfe354",
                            Email = "lcheatle13@simplemachines.org",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ccheatle13"
                        },
                        new
                        {
                            Id = 41,
                            AccessFailedCount = 0,
                            City = "Julayjilah",
                            ConcurrencyStamp = "5e302875-0e2f-414d-a041-a012b63d9b5f",
                            Email = "cadamsen14@fema.gov",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "aadamsen14"
                        },
                        new
                        {
                            Id = 42,
                            AccessFailedCount = 0,
                            City = "Dębnica Kaszubska",
                            ConcurrencyStamp = "4363097a-0b0c-4c09-9460-842e4f4666c2",
                            Email = "jmcilherran15@redcross.org",
                            EmailConfirmed = false,
                            Gender = "Genderqueer",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mmcilherran15"
                        },
                        new
                        {
                            Id = 43,
                            AccessFailedCount = 0,
                            City = "Bentar",
                            ConcurrencyStamp = "be1ae2d8-f4ae-438e-be18-13719a3fc84f",
                            Email = "mcarnock16@ycombinator.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bcarnock16"
                        },
                        new
                        {
                            Id = 44,
                            AccessFailedCount = 0,
                            City = "Miaoxi",
                            ConcurrencyStamp = "cecdf5b9-dc48-4f7a-87e6-45c1f0013608",
                            Email = "cderyebarrett17@phpbb.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "sderyebarrett17"
                        },
                        new
                        {
                            Id = 45,
                            AccessFailedCount = 0,
                            City = "Zengji",
                            ConcurrencyStamp = "059c8fe6-8e2d-433c-81ab-7728222d8add",
                            Email = "mcaldwall18@nps.gov",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ccaldwall18"
                        },
                        new
                        {
                            Id = 46,
                            AccessFailedCount = 0,
                            City = "Buawan",
                            ConcurrencyStamp = "1c5a7557-bf32-4303-923c-b57b4f44d86c",
                            Email = "tjosland19@parallels.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "njosland19"
                        },
                        new
                        {
                            Id = 47,
                            AccessFailedCount = 0,
                            City = "Kajiki",
                            ConcurrencyStamp = "afc2dff9-6cd4-4752-98a7-8643c4068ac4",
                            Email = "mpetracek1a@feedburner.com",
                            EmailConfirmed = false,
                            Gender = "Bigender",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "tpetracek1a"
                        },
                        new
                        {
                            Id = 48,
                            AccessFailedCount = 0,
                            City = "Yudaikelike",
                            ConcurrencyStamp = "636a88b2-a8e1-49e8-bf45-f27ed655e09b",
                            Email = "schisolm1b@sciencedaily.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "achisolm1b"
                        },
                        new
                        {
                            Id = 49,
                            AccessFailedCount = 0,
                            City = "Casal da Anja",
                            ConcurrencyStamp = "8e4dab62-4ac9-4356-9398-fb2815536085",
                            Email = "ksedgebeer1c@unblog.fr",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ksedgebeer1c"
                        },
                        new
                        {
                            Id = 50,
                            AccessFailedCount = 0,
                            City = "Ararat",
                            ConcurrencyStamp = "d1df6b3a-0f76-4be5-aa8d-3c38647daee5",
                            Email = "sclubley1d@google.de",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "lclubley1d"
                        },
                        new
                        {
                            Id = 51,
                            AccessFailedCount = 0,
                            City = "El Ángel",
                            ConcurrencyStamp = "aaa00f4e-cb91-4a5f-98a7-c1aa4e44a111",
                            Email = "sglassopp1e@opensource.org",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "pglassopp1e"
                        },
                        new
                        {
                            Id = 52,
                            AccessFailedCount = 0,
                            City = "Dededo Village",
                            ConcurrencyStamp = "5874ac9e-412c-4588-88ab-fc1fa7610b07",
                            Email = "fwilliamson1f@cyberchimps.com",
                            EmailConfirmed = false,
                            Gender = "Genderqueer",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "awilliamson1f"
                        },
                        new
                        {
                            Id = 53,
                            AccessFailedCount = 0,
                            City = "Zevenaar",
                            ConcurrencyStamp = "603d1bb0-5ab8-4541-9c68-0856b871be3c",
                            Email = "mvogelein1g@purevolume.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kvogelein1g"
                        },
                        new
                        {
                            Id = 54,
                            AccessFailedCount = 0,
                            City = "Topolovgrad",
                            ConcurrencyStamp = "c743b117-be41-4e57-97bb-9bf253b13979",
                            Email = "ggrigoriscu1h@dagondesign.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mgrigoriscu1h"
                        },
                        new
                        {
                            Id = 55,
                            AccessFailedCount = 0,
                            City = "Yuelai",
                            ConcurrencyStamp = "23d6be83-ddb9-45e0-a155-b6cf17af4d0c",
                            Email = "sduffitt1i@usatoday.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "sduffitt1i"
                        },
                        new
                        {
                            Id = 56,
                            AccessFailedCount = 0,
                            City = "Mencon",
                            ConcurrencyStamp = "2902b439-bfd1-4fa9-9df6-80a9ada8943e",
                            Email = "trennles1j@earthlink.net",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rrennles1j"
                        },
                        new
                        {
                            Id = 57,
                            AccessFailedCount = 0,
                            City = "Antas",
                            ConcurrencyStamp = "5a3d2b0f-560c-4a91-a5b8-123cfddb6f02",
                            Email = "mgorler1k@chicagotribune.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kgorler1k"
                        },
                        new
                        {
                            Id = 58,
                            AccessFailedCount = 0,
                            City = "Solana",
                            ConcurrencyStamp = "13b25bdc-677b-492e-973b-7186208730c2",
                            Email = "hmacadam1l@berkeley.edu",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kmacadam1l"
                        },
                        new
                        {
                            Id = 59,
                            AccessFailedCount = 0,
                            City = "Maubasa",
                            ConcurrencyStamp = "009969fe-c821-4f99-8db7-9ae88276e3ed",
                            Email = "gshrieve1m@twitpic.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ashrieve1m"
                        },
                        new
                        {
                            Id = 60,
                            AccessFailedCount = 0,
                            City = "Tuusula",
                            ConcurrencyStamp = "af826505-442f-4376-955d-ffc8cfd1e939",
                            Email = "abottleson1n@nba.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cbottleson1n"
                        },
                        new
                        {
                            Id = 61,
                            AccessFailedCount = 0,
                            City = "Bakung Utara",
                            ConcurrencyStamp = "8c3954dc-6a4f-4a26-8d6f-08cd3b8a4bc2",
                            Email = "lknightly1o@chicagotribune.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rknightly1o"
                        },
                        new
                        {
                            Id = 62,
                            AccessFailedCount = 0,
                            City = "Ipoh",
                            ConcurrencyStamp = "cff7ac10-7dbf-4164-a3ee-49188378f99b",
                            Email = "ngingle1p@mashable.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kgingle1p"
                        },
                        new
                        {
                            Id = 63,
                            AccessFailedCount = 0,
                            City = "Halmstad",
                            ConcurrencyStamp = "35255bca-2718-4672-b28e-553de7ab4119",
                            Email = "aanthill1q@miibeian.gov.cn",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "fanthill1q"
                        },
                        new
                        {
                            Id = 64,
                            AccessFailedCount = 0,
                            City = "Waitun",
                            ConcurrencyStamp = "76380c43-c300-4b0b-b536-fa49ba2d59ec",
                            Email = "tharsum1r@github.io",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "vharsum1r"
                        },
                        new
                        {
                            Id = 65,
                            AccessFailedCount = 0,
                            City = "Lugo",
                            ConcurrencyStamp = "60585ebc-beeb-4dab-bffa-d98a28d34ac6",
                            Email = "sguido1s@nymag.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bguido1s"
                        },
                        new
                        {
                            Id = 66,
                            AccessFailedCount = 0,
                            City = "Las Mesas",
                            ConcurrencyStamp = "27cf6a80-ccbe-4ff6-b7a9-d4fdb8c03d49",
                            Email = "ereuven1t@fema.gov",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "preuven1t"
                        },
                        new
                        {
                            Id = 67,
                            AccessFailedCount = 0,
                            City = "Kedungkrajan",
                            ConcurrencyStamp = "e557eb2d-a48d-45f9-acab-789c6a599c8f",
                            Email = "bmckerlie1u@altervista.org",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cmckerlie1u"
                        },
                        new
                        {
                            Id = 68,
                            AccessFailedCount = 0,
                            City = "Bangelan",
                            ConcurrencyStamp = "79aca74a-96c7-4b48-a11c-e8e504bf613d",
                            Email = "amorcom1v@soundcloud.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "amorcom1v"
                        },
                        new
                        {
                            Id = 69,
                            AccessFailedCount = 0,
                            City = "Wonorejo",
                            ConcurrencyStamp = "50f7aa44-9659-496c-8c4c-a275e47b0228",
                            Email = "jmacellen1w@sciencedirect.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "smacellen1w"
                        },
                        new
                        {
                            Id = 70,
                            AccessFailedCount = 0,
                            City = "Barranco de Loba",
                            ConcurrencyStamp = "cf9ea5af-374d-4c4f-a1ae-e165e01d4c5e",
                            Email = "msangra1x@soup.io",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "vsangra1x"
                        },
                        new
                        {
                            Id = 71,
                            AccessFailedCount = 0,
                            City = "Chendong",
                            ConcurrencyStamp = "ff73cadc-f7de-4e79-b4a8-00e84fc5b463",
                            Email = "hcinelli1y@paypal.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ecinelli1y"
                        },
                        new
                        {
                            Id = 72,
                            AccessFailedCount = 0,
                            City = "Fresno",
                            ConcurrencyStamp = "ddb84a14-ed22-409e-8510-93fdef0cd1d2",
                            Email = "cstace1z@networksolutions.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "astace1z"
                        },
                        new
                        {
                            Id = 73,
                            AccessFailedCount = 0,
                            City = "Tashtagol",
                            ConcurrencyStamp = "c215f94a-4295-4a8f-8317-470aa200f8ff",
                            Email = "rpieracci20@moonfruit.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "dpieracci20"
                        },
                        new
                        {
                            Id = 74,
                            AccessFailedCount = 0,
                            City = "Ersekë",
                            ConcurrencyStamp = "e6681029-5b92-4761-aaf6-c18588306a8f",
                            Email = "ageorghiou21@icq.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cgeorghiou21"
                        },
                        new
                        {
                            Id = 75,
                            AccessFailedCount = 0,
                            City = "Eira da Pedra",
                            ConcurrencyStamp = "9842f8aa-1a6f-497e-8fd5-6a619a81c36c",
                            Email = "creal22@sina.com.cn",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mreal22"
                        },
                        new
                        {
                            Id = 76,
                            AccessFailedCount = 0,
                            City = "Hroznětín",
                            ConcurrencyStamp = "a0ab617a-ed7f-43c3-9a76-3e50eb0736d9",
                            Email = "eheinschke23@icq.com",
                            EmailConfirmed = false,
                            Gender = "Non-binary",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "wheinschke23"
                        },
                        new
                        {
                            Id = 77,
                            AccessFailedCount = 0,
                            City = "Terter",
                            ConcurrencyStamp = "b0204f43-2818-465d-a72f-bd4a7e1e0f88",
                            Email = "bmarval24@dell.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "emarval24"
                        },
                        new
                        {
                            Id = 78,
                            AccessFailedCount = 0,
                            City = "Samara",
                            ConcurrencyStamp = "414b51a2-ebe1-4a5f-b405-454aef242c59",
                            Email = "jstothard25@hugedomains.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "istothard25"
                        },
                        new
                        {
                            Id = 79,
                            AccessFailedCount = 0,
                            City = "Jian’ou",
                            ConcurrencyStamp = "4709a312-7663-4b0b-9e05-aac9211320d9",
                            Email = "amedgewick26@meetup.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rmedgewick26"
                        },
                        new
                        {
                            Id = 80,
                            AccessFailedCount = 0,
                            City = "Dampit Satu",
                            ConcurrencyStamp = "88844aff-0d12-49cf-a66a-4233e66880e0",
                            Email = "mshawl27@bloglovin.com",
                            EmailConfirmed = false,
                            Gender = "Genderfluid",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "gshawl27"
                        },
                        new
                        {
                            Id = 81,
                            AccessFailedCount = 0,
                            City = "Columbus",
                            ConcurrencyStamp = "8fda98ae-87a2-47df-88f3-06c0846df2f4",
                            Email = "csirey28@google.fr",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "csirey28"
                        },
                        new
                        {
                            Id = 82,
                            AccessFailedCount = 0,
                            City = "Susanino",
                            ConcurrencyStamp = "4790ec28-6c94-4f08-b5f4-c02dbf7d1399",
                            Email = "lmeakin29@blinklist.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "smeakin29"
                        },
                        new
                        {
                            Id = 83,
                            AccessFailedCount = 0,
                            City = "Kuybyshevo",
                            ConcurrencyStamp = "ba264cbe-96b8-487c-87b2-3c0b42a9daaf",
                            Email = "aalleway2a@blogger.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "aalleway2a"
                        },
                        new
                        {
                            Id = 84,
                            AccessFailedCount = 0,
                            City = "Koźmin Wielkopolski",
                            ConcurrencyStamp = "82518b53-510f-4e18-869c-56cf5eed22c6",
                            Email = "lstempe2b@xinhuanet.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mstempe2b"
                        },
                        new
                        {
                            Id = 85,
                            AccessFailedCount = 0,
                            City = "Iles",
                            ConcurrencyStamp = "9c2c8423-ad5a-4b0b-9b55-18d38f48e1e6",
                            Email = "dspellar2c@e-recht24.de",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "aspellar2c"
                        },
                        new
                        {
                            Id = 86,
                            AccessFailedCount = 0,
                            City = "San José de Barlovento",
                            ConcurrencyStamp = "6c2e882f-c1c1-4916-8579-c24607849ce0",
                            Email = "hsynnot2d@typepad.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "asynnot2d"
                        },
                        new
                        {
                            Id = 87,
                            AccessFailedCount = 0,
                            City = "Las Vegas",
                            ConcurrencyStamp = "7bc8e13f-3128-43d6-b6ac-b8eafdddb708",
                            Email = "kkelsell2e@w3.org",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kkelsell2e"
                        },
                        new
                        {
                            Id = 88,
                            AccessFailedCount = 0,
                            City = "Al Ma‘baţlī",
                            ConcurrencyStamp = "8646ad6f-47fc-4a79-940f-ae2c1eb99ef5",
                            Email = "ygildea2f@msu.edu",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "lgildea2f"
                        },
                        new
                        {
                            Id = 89,
                            AccessFailedCount = 0,
                            City = "San Juan",
                            ConcurrencyStamp = "c6d412f0-bdf3-4e38-8d70-1c2cb5f77ece",
                            Email = "ccoraini2g@forbes.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ncoraini2g"
                        },
                        new
                        {
                            Id = 90,
                            AccessFailedCount = 0,
                            City = "Mandala",
                            ConcurrencyStamp = "746bcb8d-b5c2-4a7f-8499-b3274f832132",
                            Email = "srobertazzi2h@stanford.edu",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "crobertazzi2h"
                        },
                        new
                        {
                            Id = 91,
                            AccessFailedCount = 0,
                            City = "Didi Lilo",
                            ConcurrencyStamp = "88facad2-d5b3-4efa-b07f-acfdbd309d8f",
                            Email = "aroache2i@miitbeian.gov.cn",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "hroache2i"
                        },
                        new
                        {
                            Id = 92,
                            AccessFailedCount = 0,
                            City = "Piedecuesta",
                            ConcurrencyStamp = "831f921c-cd0f-4708-b342-d9d817bfb28e",
                            Email = "wkilshall2j@ycombinator.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "pkilshall2j"
                        },
                        new
                        {
                            Id = 93,
                            AccessFailedCount = 0,
                            City = "Coronda",
                            ConcurrencyStamp = "8b035dc6-4cd4-4760-9ce7-65c73631d44e",
                            Email = "bperris2k@infoseek.co.jp",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "eperris2k"
                        },
                        new
                        {
                            Id = 94,
                            AccessFailedCount = 0,
                            City = "La Mesa",
                            ConcurrencyStamp = "be96df19-2121-4867-b36a-8a2bff252897",
                            Email = "dvarndall2l@technorati.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "fvarndall2l"
                        },
                        new
                        {
                            Id = 95,
                            AccessFailedCount = 0,
                            City = "Bobon",
                            ConcurrencyStamp = "9bdb38a4-d65c-402d-b0d9-57d010718c5f",
                            Email = "nnieass2m@discovery.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "knieass2m"
                        },
                        new
                        {
                            Id = 96,
                            AccessFailedCount = 0,
                            City = "Kemlya",
                            ConcurrencyStamp = "7d1020d4-2bfc-4a12-ac71-faf4d0a047b5",
                            Email = "akloisner2n@berkeley.edu",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kkloisner2n"
                        },
                        new
                        {
                            Id = 97,
                            AccessFailedCount = 0,
                            City = "Leipzig",
                            ConcurrencyStamp = "490cef03-ed58-4deb-b9c3-bef53ddb0cee",
                            Email = "gmorforth2o@cafepress.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "gmorforth2o"
                        },
                        new
                        {
                            Id = 98,
                            AccessFailedCount = 0,
                            City = "Muricay",
                            ConcurrencyStamp = "5c83be9a-f926-4c75-ba77-bddf047c88eb",
                            Email = "qcookney2p@statcounter.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "acookney2p"
                        },
                        new
                        {
                            Id = 99,
                            AccessFailedCount = 0,
                            City = "Strängnäs",
                            ConcurrencyStamp = "54adfdea-f79b-46db-a7a6-637cff0b594e",
                            Email = "ehawtin2q@wired.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mhawtin2q"
                        },
                        new
                        {
                            Id = 100,
                            AccessFailedCount = 0,
                            City = "Bat Khela",
                            ConcurrencyStamp = "4cc241b0-af27-4b60-847d-d959c8bcd4c5",
                            Email = "khinge2r@trellian.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rhinge2r"
                        });
                });

            modelBuilder.Entity("webapi.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("webapi.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("webapi.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("webapi.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("webapi.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("webapi.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("webapi.Entities.AppUserRole", b =>
                {
                    b.HasOne("webapi.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("webapi.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("webapi.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
