// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231002035652_identityaddednew")]
    partial class identityaddednew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("webapi.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("webapi.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            City = "Zhaoguli",
                            ConcurrencyStamp = "b2fc3a0c-2bbc-4fcb-935a-d5dc19648d61",
                            Email = "wkubach0@nature.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ckubach0"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            City = "Paraíso das Águas",
                            ConcurrencyStamp = "24fe046f-9035-4088-afb3-dc7325a5e32e",
                            Email = "gmickleburgh1@spotify.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "jmickleburgh1"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            City = "Boyarka",
                            ConcurrencyStamp = "312b2dec-a8c9-4167-81b8-376d3efcd4a0",
                            Email = "gdurante2@state.gov",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "wdurante2"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            City = "Seixal",
                            ConcurrencyStamp = "76a742d0-f7b7-4804-8175-49d714d616b5",
                            Email = "iwoollett3@yelp.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "gwoollett3"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            City = "Saint-Pierre",
                            ConcurrencyStamp = "33db083c-59fa-4dee-907a-5d6adf2a4c0a",
                            Email = "mwrey4@dot.gov",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "awrey4"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            City = "Teminabuan",
                            ConcurrencyStamp = "64bef25e-4465-428c-956b-c214058ae9c7",
                            Email = "stimlett5@ihg.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mtimlett5"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            City = "Shuangnian",
                            ConcurrencyStamp = "75f1e0b1-ac2b-4b20-b2b6-5e19d26f3897",
                            Email = "ltrimbey6@hc360.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "btrimbey6"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            City = "Changqing",
                            ConcurrencyStamp = "1cc3e71e-bb1a-4a20-b24e-7d8ed3f5c8a0",
                            Email = "lgirogetti7@example.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cgirogetti7"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            City = "Eusebio Ayala",
                            ConcurrencyStamp = "168f5d00-eaac-44f5-96f0-2a117eb06ff2",
                            Email = "rbocken8@nifty.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "tbocken8"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            City = "Higashimurayama-shi",
                            ConcurrencyStamp = "2e72a35c-ab8c-44a2-9a73-44ce072055c6",
                            Email = "dsawer9@netvibes.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ssawer9"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            City = "Las Americas",
                            ConcurrencyStamp = "854725cd-9ea5-4602-9dc1-97077b9a5593",
                            Email = "pperfecta@goo.ne.jp",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rperfecta"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            City = "Rantepang",
                            ConcurrencyStamp = "d8c3bc9e-eccd-4f98-8632-6a07e5496d38",
                            Email = "maxcelb@home.pl",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "naxcelb"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            City = "Dagang",
                            ConcurrencyStamp = "5142a6c1-d3e1-4c84-864d-8737f9acd7ea",
                            Email = "keykelboschc@joomla.org",
                            EmailConfirmed = false,
                            Gender = "Genderqueer",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "meykelboschc"
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            City = "Al Qardāḩah",
                            ConcurrencyStamp = "a546381d-9f70-4554-ab6e-2b15bf124626",
                            Email = "nbamletd@europa.eu",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cbamletd"
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            City = "Dobryanka",
                            ConcurrencyStamp = "78165757-8235-42b1-86b9-9eccfcd595dc",
                            Email = "sgarritleye@qq.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "dgarritleye"
                        },
                        new
                        {
                            Id = 16,
                            AccessFailedCount = 0,
                            City = "Rockford",
                            ConcurrencyStamp = "40f322d1-7cf2-4ff1-b01b-63c8d1e88197",
                            Email = "mlockf@amazon.co.uk",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "klockf"
                        },
                        new
                        {
                            Id = 17,
                            AccessFailedCount = 0,
                            City = "Victoria",
                            ConcurrencyStamp = "d6a3294a-a938-44a1-b4db-17bf472c9328",
                            Email = "rharbachg@hud.gov",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "pharbachg"
                        },
                        new
                        {
                            Id = 18,
                            AccessFailedCount = 0,
                            City = "Kamālia",
                            ConcurrencyStamp = "9a8bb61e-c1a8-4ea5-b75a-f9c0af3cc546",
                            Email = "mtomneyh@zdnet.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "stomneyh"
                        },
                        new
                        {
                            Id = 19,
                            AccessFailedCount = 0,
                            City = "Erdao",
                            ConcurrencyStamp = "034fc5b5-8284-436f-a82d-e9ec93835ea9",
                            Email = "mcestardi@g.co",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bcestardi"
                        },
                        new
                        {
                            Id = 20,
                            AccessFailedCount = 0,
                            City = "Holboo",
                            ConcurrencyStamp = "aafb6c91-7096-46ed-b20b-7cfa9275efc2",
                            Email = "ktopperj@cbc.ca",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rtopperj"
                        },
                        new
                        {
                            Id = 21,
                            AccessFailedCount = 0,
                            City = "Três Coroas",
                            ConcurrencyStamp = "ecac3ce2-f7e0-4e35-a202-a6befae1d5c8",
                            Email = "mworthyk@deliciousdays.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kworthyk"
                        },
                        new
                        {
                            Id = 22,
                            AccessFailedCount = 0,
                            City = "Gibgos",
                            ConcurrencyStamp = "62174e7a-c256-471a-9fcf-2077b29b914f",
                            Email = "kitscovitzl@go.com",
                            EmailConfirmed = false,
                            Gender = "Agender",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mitscovitzl"
                        },
                        new
                        {
                            Id = 23,
                            AccessFailedCount = 0,
                            City = "São João Nepomuceno",
                            ConcurrencyStamp = "1321a8a1-b7e5-4d52-bd20-cbde14a133ea",
                            Email = "lfitterm@earthlink.net",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "sfitterm"
                        },
                        new
                        {
                            Id = 24,
                            AccessFailedCount = 0,
                            City = "Sokolo",
                            ConcurrencyStamp = "5593cd36-e108-4bdd-a476-bb162b038ca8",
                            Email = "dthorsbyn@xrea.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "dthorsbyn"
                        },
                        new
                        {
                            Id = 25,
                            AccessFailedCount = 0,
                            City = "Pamplona/Iruña",
                            ConcurrencyStamp = "9bc805e1-4d03-4a33-aead-5e86456cdfa3",
                            Email = "apeeryo@rakuten.co.jp",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ppeeryo"
                        },
                        new
                        {
                            Id = 26,
                            AccessFailedCount = 0,
                            City = "Telagasari",
                            ConcurrencyStamp = "19310753-d5ca-4fd2-91de-f55a29ffdd6e",
                            Email = "ftathacottp@nytimes.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "dtathacottp"
                        },
                        new
                        {
                            Id = 27,
                            AccessFailedCount = 0,
                            City = "Tikhoretsk",
                            ConcurrencyStamp = "99f3de16-b32a-4fc8-aa44-e782fa55b608",
                            Email = "blingwoodq@jigsy.com",
                            EmailConfirmed = false,
                            Gender = "Genderfluid",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mlingwoodq"
                        },
                        new
                        {
                            Id = 28,
                            AccessFailedCount = 0,
                            City = "Rokytne",
                            ConcurrencyStamp = "a7fcb6a4-042c-4a9b-bd1f-62459568bedf",
                            Email = "jrichesr@tiny.cc",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "krichesr"
                        },
                        new
                        {
                            Id = 29,
                            AccessFailedCount = 0,
                            City = "Motuo",
                            ConcurrencyStamp = "092f712e-9c77-43ab-aa4e-81d284743d8c",
                            Email = "cmaiers@vkontakte.ru",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "lmaiers"
                        },
                        new
                        {
                            Id = 30,
                            AccessFailedCount = 0,
                            City = "Smiltene",
                            ConcurrencyStamp = "00442f7f-3c12-44c3-bf89-6556a7803db6",
                            Email = "pjeannessont@deviantart.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ljeannessont"
                        },
                        new
                        {
                            Id = 31,
                            AccessFailedCount = 0,
                            City = "Río Cuarto",
                            ConcurrencyStamp = "6e239fcf-d61d-47a8-8632-d8b5f25df705",
                            Email = "smolsonu@youku.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bmolsonu"
                        },
                        new
                        {
                            Id = 32,
                            AccessFailedCount = 0,
                            City = "Lugui",
                            ConcurrencyStamp = "6834b92d-cb0c-43b1-ac8a-5f57e281604c",
                            Email = "hgrocockv@bloglines.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "lgrocockv"
                        },
                        new
                        {
                            Id = 33,
                            AccessFailedCount = 0,
                            City = "Dachnoye",
                            ConcurrencyStamp = "84960557-4416-45a4-87f7-69dc2a19fa66",
                            Email = "mlessmarew@prnewswire.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "alessmarew"
                        },
                        new
                        {
                            Id = 34,
                            AccessFailedCount = 0,
                            City = "Modot",
                            ConcurrencyStamp = "49a9ba6e-0033-4d9d-a711-55b7412bce2b",
                            Email = "jpadfieldx@hud.gov",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cpadfieldx"
                        },
                        new
                        {
                            Id = 35,
                            AccessFailedCount = 0,
                            City = "Marsh Harbour",
                            ConcurrencyStamp = "7916821b-c94e-463a-a8fd-d009a4f4fc8e",
                            Email = "hhaggerwoody@telegraph.co.uk",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "phaggerwoody"
                        },
                        new
                        {
                            Id = 36,
                            AccessFailedCount = 0,
                            City = "Lianzhu",
                            ConcurrencyStamp = "26089839-7d65-4e44-bf67-b82a24736d4b",
                            Email = "dsandfordz@cnbc.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "lsandfordz"
                        },
                        new
                        {
                            Id = 37,
                            AccessFailedCount = 0,
                            City = "Hněvotín",
                            ConcurrencyStamp = "203c1b91-1920-4a81-a63b-321524de53c6",
                            Email = "kboal10@fda.gov",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bboal10"
                        },
                        new
                        {
                            Id = 38,
                            AccessFailedCount = 0,
                            City = "Sydney",
                            ConcurrencyStamp = "efba8c8a-4cce-4e6d-8410-8c80596d8184",
                            Email = "echalloner11@ucsd.edu",
                            EmailConfirmed = false,
                            Gender = "Genderqueer",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "gchalloner11"
                        },
                        new
                        {
                            Id = 39,
                            AccessFailedCount = 0,
                            City = "Hechuan",
                            ConcurrencyStamp = "c8585739-fbf2-4fc0-b8fa-83f54afad8e3",
                            Email = "duzzell12@lulu.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "luzzell12"
                        },
                        new
                        {
                            Id = 40,
                            AccessFailedCount = 0,
                            City = "Krajan Timur Suger Kidul",
                            ConcurrencyStamp = "5bb877d7-5ab0-4ab2-b5d4-e1aa84311863",
                            Email = "lcheatle13@simplemachines.org",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ccheatle13"
                        },
                        new
                        {
                            Id = 41,
                            AccessFailedCount = 0,
                            City = "Julayjilah",
                            ConcurrencyStamp = "198cb810-3cb4-4b9f-8a3d-35bdcf260cd4",
                            Email = "cadamsen14@fema.gov",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "aadamsen14"
                        },
                        new
                        {
                            Id = 42,
                            AccessFailedCount = 0,
                            City = "Dębnica Kaszubska",
                            ConcurrencyStamp = "2b6f08ee-bbca-4c30-81b2-177c56b73580",
                            Email = "jmcilherran15@redcross.org",
                            EmailConfirmed = false,
                            Gender = "Genderqueer",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mmcilherran15"
                        },
                        new
                        {
                            Id = 43,
                            AccessFailedCount = 0,
                            City = "Bentar",
                            ConcurrencyStamp = "94843108-3f5b-4abf-b522-51013fb1b00c",
                            Email = "mcarnock16@ycombinator.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bcarnock16"
                        },
                        new
                        {
                            Id = 44,
                            AccessFailedCount = 0,
                            City = "Miaoxi",
                            ConcurrencyStamp = "7175a1aa-60e1-43ec-8519-52dbff76e3ce",
                            Email = "cderyebarrett17@phpbb.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "sderyebarrett17"
                        },
                        new
                        {
                            Id = 45,
                            AccessFailedCount = 0,
                            City = "Zengji",
                            ConcurrencyStamp = "def2a424-7ee9-468f-9f29-2b4ccad706eb",
                            Email = "mcaldwall18@nps.gov",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ccaldwall18"
                        },
                        new
                        {
                            Id = 46,
                            AccessFailedCount = 0,
                            City = "Buawan",
                            ConcurrencyStamp = "baaa7ee4-2566-490d-8b4a-6ad800b5ea57",
                            Email = "tjosland19@parallels.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "njosland19"
                        },
                        new
                        {
                            Id = 47,
                            AccessFailedCount = 0,
                            City = "Kajiki",
                            ConcurrencyStamp = "11e6e53b-c930-4180-aa06-d76c229cc561",
                            Email = "mpetracek1a@feedburner.com",
                            EmailConfirmed = false,
                            Gender = "Bigender",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "tpetracek1a"
                        },
                        new
                        {
                            Id = 48,
                            AccessFailedCount = 0,
                            City = "Yudaikelike",
                            ConcurrencyStamp = "598778f7-a2b9-4ad3-b43b-b6127e3a5845",
                            Email = "schisolm1b@sciencedaily.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "achisolm1b"
                        },
                        new
                        {
                            Id = 49,
                            AccessFailedCount = 0,
                            City = "Casal da Anja",
                            ConcurrencyStamp = "3443f4f7-72bb-4037-8153-ab632cd7dc49",
                            Email = "ksedgebeer1c@unblog.fr",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ksedgebeer1c"
                        },
                        new
                        {
                            Id = 50,
                            AccessFailedCount = 0,
                            City = "Ararat",
                            ConcurrencyStamp = "ae6957f7-6050-452b-892f-8dfe1aced60a",
                            Email = "sclubley1d@google.de",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "lclubley1d"
                        },
                        new
                        {
                            Id = 51,
                            AccessFailedCount = 0,
                            City = "El Ángel",
                            ConcurrencyStamp = "d8a5194d-f8e9-4577-82f9-9dc66315d075",
                            Email = "sglassopp1e@opensource.org",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "pglassopp1e"
                        },
                        new
                        {
                            Id = 52,
                            AccessFailedCount = 0,
                            City = "Dededo Village",
                            ConcurrencyStamp = "f5873359-143b-4c8a-81ac-0aec7a890557",
                            Email = "fwilliamson1f@cyberchimps.com",
                            EmailConfirmed = false,
                            Gender = "Genderqueer",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "awilliamson1f"
                        },
                        new
                        {
                            Id = 53,
                            AccessFailedCount = 0,
                            City = "Zevenaar",
                            ConcurrencyStamp = "671cbd62-4d64-491d-b678-1ae0e7dcc658",
                            Email = "mvogelein1g@purevolume.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kvogelein1g"
                        },
                        new
                        {
                            Id = 54,
                            AccessFailedCount = 0,
                            City = "Topolovgrad",
                            ConcurrencyStamp = "dccea47d-b52a-416b-b5f0-185c57106059",
                            Email = "ggrigoriscu1h@dagondesign.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mgrigoriscu1h"
                        },
                        new
                        {
                            Id = 55,
                            AccessFailedCount = 0,
                            City = "Yuelai",
                            ConcurrencyStamp = "79628c01-8e80-4091-aa11-b09b6a417be5",
                            Email = "sduffitt1i@usatoday.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "sduffitt1i"
                        },
                        new
                        {
                            Id = 56,
                            AccessFailedCount = 0,
                            City = "Mencon",
                            ConcurrencyStamp = "f5e4bba2-f950-410c-b280-8b940cd08855",
                            Email = "trennles1j@earthlink.net",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rrennles1j"
                        },
                        new
                        {
                            Id = 57,
                            AccessFailedCount = 0,
                            City = "Antas",
                            ConcurrencyStamp = "4274e873-a733-4467-afea-ba00c8c5d978",
                            Email = "mgorler1k@chicagotribune.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kgorler1k"
                        },
                        new
                        {
                            Id = 58,
                            AccessFailedCount = 0,
                            City = "Solana",
                            ConcurrencyStamp = "792fd56a-6bba-4206-8c38-c6e0b021e2e7",
                            Email = "hmacadam1l@berkeley.edu",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kmacadam1l"
                        },
                        new
                        {
                            Id = 59,
                            AccessFailedCount = 0,
                            City = "Maubasa",
                            ConcurrencyStamp = "a2896e2a-2144-40ed-87b4-01f09cdba0ea",
                            Email = "gshrieve1m@twitpic.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ashrieve1m"
                        },
                        new
                        {
                            Id = 60,
                            AccessFailedCount = 0,
                            City = "Tuusula",
                            ConcurrencyStamp = "30ef8ea2-c134-42d3-bf04-eb8c0b29ef2e",
                            Email = "abottleson1n@nba.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cbottleson1n"
                        },
                        new
                        {
                            Id = 61,
                            AccessFailedCount = 0,
                            City = "Bakung Utara",
                            ConcurrencyStamp = "05d9415b-366d-4379-a75e-5668d3853315",
                            Email = "lknightly1o@chicagotribune.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rknightly1o"
                        },
                        new
                        {
                            Id = 62,
                            AccessFailedCount = 0,
                            City = "Ipoh",
                            ConcurrencyStamp = "bdd4903d-b6a3-493c-98b7-975be4ce7679",
                            Email = "ngingle1p@mashable.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kgingle1p"
                        },
                        new
                        {
                            Id = 63,
                            AccessFailedCount = 0,
                            City = "Halmstad",
                            ConcurrencyStamp = "da3c183c-86b8-4918-85c7-7f95ce0b6a06",
                            Email = "aanthill1q@miibeian.gov.cn",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "fanthill1q"
                        },
                        new
                        {
                            Id = 64,
                            AccessFailedCount = 0,
                            City = "Waitun",
                            ConcurrencyStamp = "05beb465-8fe8-4eb3-b9c9-8021cbe8d02d",
                            Email = "tharsum1r@github.io",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "vharsum1r"
                        },
                        new
                        {
                            Id = 65,
                            AccessFailedCount = 0,
                            City = "Lugo",
                            ConcurrencyStamp = "20e95f24-f98a-4147-94a3-6458dbb9e1bc",
                            Email = "sguido1s@nymag.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bguido1s"
                        },
                        new
                        {
                            Id = 66,
                            AccessFailedCount = 0,
                            City = "Las Mesas",
                            ConcurrencyStamp = "6f31ba98-58a2-4d91-8a26-a685bb65c6d5",
                            Email = "ereuven1t@fema.gov",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "preuven1t"
                        },
                        new
                        {
                            Id = 67,
                            AccessFailedCount = 0,
                            City = "Kedungkrajan",
                            ConcurrencyStamp = "e776ddad-217c-4fb5-8653-87f92206f046",
                            Email = "bmckerlie1u@altervista.org",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cmckerlie1u"
                        },
                        new
                        {
                            Id = 68,
                            AccessFailedCount = 0,
                            City = "Bangelan",
                            ConcurrencyStamp = "af2afc20-a1a9-4aee-b0b0-30b18c695090",
                            Email = "amorcom1v@soundcloud.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "amorcom1v"
                        },
                        new
                        {
                            Id = 69,
                            AccessFailedCount = 0,
                            City = "Wonorejo",
                            ConcurrencyStamp = "111deb7b-bf6a-4a10-9ad7-7169e9b5e8cc",
                            Email = "jmacellen1w@sciencedirect.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "smacellen1w"
                        },
                        new
                        {
                            Id = 70,
                            AccessFailedCount = 0,
                            City = "Barranco de Loba",
                            ConcurrencyStamp = "7a70a6dd-7799-4e3b-9aa0-a52e0f8db31f",
                            Email = "msangra1x@soup.io",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "vsangra1x"
                        },
                        new
                        {
                            Id = 71,
                            AccessFailedCount = 0,
                            City = "Chendong",
                            ConcurrencyStamp = "22496f0c-4809-46b1-809c-0513d33cb84f",
                            Email = "hcinelli1y@paypal.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ecinelli1y"
                        },
                        new
                        {
                            Id = 72,
                            AccessFailedCount = 0,
                            City = "Fresno",
                            ConcurrencyStamp = "a2815382-dd9a-4c8a-92aa-a3cd532f387e",
                            Email = "cstace1z@networksolutions.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "astace1z"
                        },
                        new
                        {
                            Id = 73,
                            AccessFailedCount = 0,
                            City = "Tashtagol",
                            ConcurrencyStamp = "56108041-4866-4e52-9ee5-7cd7aa91964c",
                            Email = "rpieracci20@moonfruit.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "dpieracci20"
                        },
                        new
                        {
                            Id = 74,
                            AccessFailedCount = 0,
                            City = "Ersekë",
                            ConcurrencyStamp = "7758e9c7-7dbe-48f8-935e-0dcc94a6d019",
                            Email = "ageorghiou21@icq.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "cgeorghiou21"
                        },
                        new
                        {
                            Id = 75,
                            AccessFailedCount = 0,
                            City = "Eira da Pedra",
                            ConcurrencyStamp = "8cb2ae33-12d6-4732-8ede-82f2192673fd",
                            Email = "creal22@sina.com.cn",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mreal22"
                        },
                        new
                        {
                            Id = 76,
                            AccessFailedCount = 0,
                            City = "Hroznětín",
                            ConcurrencyStamp = "ed412214-0a2d-437e-aa59-73a4f173ebe0",
                            Email = "eheinschke23@icq.com",
                            EmailConfirmed = false,
                            Gender = "Non-binary",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "wheinschke23"
                        },
                        new
                        {
                            Id = 77,
                            AccessFailedCount = 0,
                            City = "Terter",
                            ConcurrencyStamp = "6eeb4cbd-4d09-4bf3-a9ce-4edf6f4f9cef",
                            Email = "bmarval24@dell.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "emarval24"
                        },
                        new
                        {
                            Id = 78,
                            AccessFailedCount = 0,
                            City = "Samara",
                            ConcurrencyStamp = "ecd5c8d0-f095-4936-a4d3-f6b57314cd12",
                            Email = "jstothard25@hugedomains.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "istothard25"
                        },
                        new
                        {
                            Id = 79,
                            AccessFailedCount = 0,
                            City = "Jian’ou",
                            ConcurrencyStamp = "010727fd-db33-4feb-aa74-f9f213960a86",
                            Email = "amedgewick26@meetup.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rmedgewick26"
                        },
                        new
                        {
                            Id = 80,
                            AccessFailedCount = 0,
                            City = "Dampit Satu",
                            ConcurrencyStamp = "679d5be2-38bd-4106-9134-78a2e1e62b38",
                            Email = "mshawl27@bloglovin.com",
                            EmailConfirmed = false,
                            Gender = "Genderfluid",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "gshawl27"
                        },
                        new
                        {
                            Id = 81,
                            AccessFailedCount = 0,
                            City = "Columbus",
                            ConcurrencyStamp = "5c385f93-48af-4b78-9c13-f41851d797dd",
                            Email = "csirey28@google.fr",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "csirey28"
                        },
                        new
                        {
                            Id = 82,
                            AccessFailedCount = 0,
                            City = "Susanino",
                            ConcurrencyStamp = "d2f4e03e-15d6-4a69-94a1-eaccbae497a8",
                            Email = "lmeakin29@blinklist.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "smeakin29"
                        },
                        new
                        {
                            Id = 83,
                            AccessFailedCount = 0,
                            City = "Kuybyshevo",
                            ConcurrencyStamp = "6ef8e036-0ab1-4cc1-8d1b-910be54378e5",
                            Email = "aalleway2a@blogger.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "aalleway2a"
                        },
                        new
                        {
                            Id = 84,
                            AccessFailedCount = 0,
                            City = "Koźmin Wielkopolski",
                            ConcurrencyStamp = "8f459cdb-2b49-4325-878e-34ea41a498c2",
                            Email = "lstempe2b@xinhuanet.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mstempe2b"
                        },
                        new
                        {
                            Id = 85,
                            AccessFailedCount = 0,
                            City = "Iles",
                            ConcurrencyStamp = "a890c52a-c128-44fc-a016-65197e03381b",
                            Email = "dspellar2c@e-recht24.de",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "aspellar2c"
                        },
                        new
                        {
                            Id = 86,
                            AccessFailedCount = 0,
                            City = "San José de Barlovento",
                            ConcurrencyStamp = "d051c1d3-7ae8-4d55-addf-68882ae77d51",
                            Email = "hsynnot2d@typepad.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "asynnot2d"
                        },
                        new
                        {
                            Id = 87,
                            AccessFailedCount = 0,
                            City = "Las Vegas",
                            ConcurrencyStamp = "98f56e03-19e5-436f-af42-2a91e97a5404",
                            Email = "kkelsell2e@w3.org",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kkelsell2e"
                        },
                        new
                        {
                            Id = 88,
                            AccessFailedCount = 0,
                            City = "Al Ma‘baţlī",
                            ConcurrencyStamp = "738a05be-0c44-49d5-8b2a-8cfd31045534",
                            Email = "ygildea2f@msu.edu",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "lgildea2f"
                        },
                        new
                        {
                            Id = 89,
                            AccessFailedCount = 0,
                            City = "San Juan",
                            ConcurrencyStamp = "e1487b3f-2954-4eb1-b5f7-c6140e90ef1f",
                            Email = "ccoraini2g@forbes.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ncoraini2g"
                        },
                        new
                        {
                            Id = 90,
                            AccessFailedCount = 0,
                            City = "Mandala",
                            ConcurrencyStamp = "2a4b3090-7845-482c-8b30-87e6d92b938c",
                            Email = "srobertazzi2h@stanford.edu",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "crobertazzi2h"
                        },
                        new
                        {
                            Id = 91,
                            AccessFailedCount = 0,
                            City = "Didi Lilo",
                            ConcurrencyStamp = "61ef5db3-b2da-4d67-86e1-c1fbd5141f72",
                            Email = "aroache2i@miitbeian.gov.cn",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "hroache2i"
                        },
                        new
                        {
                            Id = 92,
                            AccessFailedCount = 0,
                            City = "Piedecuesta",
                            ConcurrencyStamp = "3d4d314e-2f94-467c-81d6-1dc765ca1aea",
                            Email = "wkilshall2j@ycombinator.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "pkilshall2j"
                        },
                        new
                        {
                            Id = 93,
                            AccessFailedCount = 0,
                            City = "Coronda",
                            ConcurrencyStamp = "27005127-9fd1-4d49-a2ea-6c4dfbe52586",
                            Email = "bperris2k@infoseek.co.jp",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "eperris2k"
                        },
                        new
                        {
                            Id = 94,
                            AccessFailedCount = 0,
                            City = "La Mesa",
                            ConcurrencyStamp = "8931c5c0-c751-4c34-8afe-50e3e56c14d5",
                            Email = "dvarndall2l@technorati.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "fvarndall2l"
                        },
                        new
                        {
                            Id = 95,
                            AccessFailedCount = 0,
                            City = "Bobon",
                            ConcurrencyStamp = "b805b5a5-c506-4394-b7a4-e97786fa4417",
                            Email = "nnieass2m@discovery.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "knieass2m"
                        },
                        new
                        {
                            Id = 96,
                            AccessFailedCount = 0,
                            City = "Kemlya",
                            ConcurrencyStamp = "52567716-2428-4f03-8033-de56b5a3dd48",
                            Email = "akloisner2n@berkeley.edu",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kkloisner2n"
                        },
                        new
                        {
                            Id = 97,
                            AccessFailedCount = 0,
                            City = "Leipzig",
                            ConcurrencyStamp = "6c55b206-c5dd-4a5a-89ce-a595564bb4fc",
                            Email = "gmorforth2o@cafepress.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "gmorforth2o"
                        },
                        new
                        {
                            Id = 98,
                            AccessFailedCount = 0,
                            City = "Muricay",
                            ConcurrencyStamp = "97ba9e8f-4489-4f1d-916f-863326fc0d21",
                            Email = "qcookney2p@statcounter.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "acookney2p"
                        },
                        new
                        {
                            Id = 99,
                            AccessFailedCount = 0,
                            City = "Strängnäs",
                            ConcurrencyStamp = "191f9e17-9c10-41b7-aa94-8fd725359d3f",
                            Email = "ehawtin2q@wired.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mhawtin2q"
                        },
                        new
                        {
                            Id = 100,
                            AccessFailedCount = 0,
                            City = "Bat Khela",
                            ConcurrencyStamp = "b3f95c9b-c24a-4f72-bbf5-1f1fded8f336",
                            Email = "khinge2r@trellian.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "rhinge2r"
                        });
                });

            modelBuilder.Entity("webapi.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("webapi.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("webapi.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("webapi.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("webapi.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("webapi.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("webapi.Entities.AppUserRole", b =>
                {
                    b.HasOne("webapi.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("webapi.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("webapi.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
